[config]
reduce_output = false

[tasks.9ccrs]
description = "Check if binaries compiled by 9ccrs works as expected"
#condition = { platforms = ["linux"], fail_message = "Only Linux is supported" }
script_runner = "@duckscript"
script = '''
fn test
  expected = set ${1}
  input = set ${2}

  o = exec cargo run "--" ${input}
  if not eq ${o.code} 0
    echo "Test failed: Failed to compile ${input}"
    exit 1
  end
  writefile tmp.s ${o.stdout}

  o = exec gcc -o tmp.exe tmp.s
  if not eq ${o.code} 0
    echo "Test failed: Generated assembly is not valid"
    exit 1
  end

  o = exec ./tmp.exe
  if not eq ${o.code} ${expected}
    echo "Test failed: ${expected} expected, but got ${o.code}"
    exit 1
  end
end

test 0 0
test 42 42

echo "All tests passed"
'''
